### ISSUE TITLE
Missing `dep init` step

### ISSUE THREAD

**Issue by localhostdotdev** [heroku/go-getting-started#11]
Otherwise the go buildpack doesn't recognize it as a go app.

Also `metadata.heroku["root-package"]` is needed in `Gopkg.toml`.

e.g. in my case:

```toml
[metadata.heroku]
  root-package = "github.com/localhostdotdev/mitmengine-web"
```
